title: Using Azure Machine Learning
description: Microsoft labs for learning to build models and create services with Azure Machine Learning
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/learnAnalytics-UsingAzureMachineLearningforAIWorkloads